<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SpiceAuth.Application\SpiceAuth.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.DataProtection" Version="8.0.11" />
      
    <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.1.0" />
      
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.11" />
      
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
      
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.11" />
      
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.1.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Data\Migrations\" />
    <Folder Include="ExternalApis\" />
    <Folder Include="Repositories\" />
    <Folder Include="Security\" />
    <Folder Include="SignalR\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
